name: rspamd

on:
  push:
    branches:
      - main
    paths:
      - 'rspamd/**'
  pull_request:
    paths:
      - 'rspamd/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: rspamd/Dockerfile
          ignore: DL3018
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1
      - name: Login to container registry
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      - name: Prepare tags
        id: prep
        run: |
          IMAGE=ectobit/rspamd
          BASE_IMAGE_VERSION=$(grep FROM rspamd/Dockerfile | awk '{ print $2 }' | cut -d ':' -f 2)
          BIN_VERSION=$(docker run --rm alpine:${BASE_IMAGE_VERSION} /bin/sh -c 'apk info --no-cache -a rspamd | sed "3q;d" | cut -d " " -f1 | cut -d- -f2')
          VERSION="${BIN_VERSION}-alpine${BASE_IMAGE_VERSION}"
          TAGS="${IMAGE}:${VERSION},${IMAGE}:${GITHUB_SHA::8},${IMAGE}:latest"
          echo ${TAGS}
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      - name: Build and push image to container registry
        uses: docker/build-push-action@v6.8.0
        with:
          context: rspamd
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: |
            org.opencontainers.image.title=rspamd
            org.opencontainers.image.description='Alpine based container image with rspamd'
            org.opencontainers.image.url=${{ github.event.repository.html_url }}/tree/main/rspamd
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.version=${{ steps.prep.outputs.version }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=BSD-2-Clause-Patent
            org.opencontainers.image.vendor=ectobit.com
            io.artifacthub.package.readme-url=https://raw.githubusercontent.com/ectobit/container-images/main/rspamd/README.md
